require('core.options')
require('core.keymaps')
require('core.colorscheme')

require('packer-config')

require('plugins.comment')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.nvim-cmp')
require('plugins.lsp')
require('plugins.lsp-signature')
require('plugins.nvim-autopairs')
